export enum EVENTS {
  COMPLETE = "COMPLETE",
  RANDOM_IN_GRADIENT = "RANDOM_IN_GRADIENT",
  RANDOMIZE = "RANDOMIZE",

  ERROR = "ERROR",

  EXECUTE_CMD = "EXECUTE_CMD",

  EXECUTION_START = "EXECUTION_START",
  EXECUTION_END = "EXECUTION_END",

  VALIDATION_START = "VALIDATION_START",
  VALIDATION_END = "VALIDATION_END",
}

export enum CMD {
  RANDOMIZE = "CMD_RANDOMIZE",
  RANDOM_IN_GRADIENT = "CMD_RANDOM_IN_GRADIENT",
  FOOBAR = "CMD_FOOBAR",
}
