export enum EVENTS {
  COMPLETE = "COMPLETE",
  RANDOM_IN_GRADIENT = "RANDOM_IN_GRADIENT",
  RANDOMIZE = "RANDOMIZE",

  ERROR = "ERROR",

  START_EXECUTION = "START_EXECUTION",
  END_EXECUTION = "END_EXECUTION",
}
